<?php

namespace App\Tests\Service\Words;

use App\Service\Words\SentenceAnalyser;
use App\Service\Words\WordDTO;
use PHPUnit\Framework\TestCase;

class DoctrineFetchTest extends TestCase
{
    private SentenceAnalyser $sentenceAnalyser;

    protected function setUp() {
        $this->sentenceAnalyser = new SentenceAnalyser();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetWordsFromSentenceReturnsWordsWithThreeLettersOrLonger() {
        $inputSentence = '  fo o foo foo ';
        $expectedWord = new WordDTO();
        $expectedWord->word = 'foo';
        $expectedWord->count = 2;

        $result = $this->sentenceAnalyser->getWordsFromSentence($inputSentence);

        $this->assertEquals([$expectedWord], $result);
    }

    public function testGetWordsFromSentenceIgnoresNonLatinWordsCharacters() {
        $inputSentence = '1.f k2n $!x.d źþð';
        $expectedWord = new WordDTO();
        $expectedWord->word = 'k2n';
        $expectedWord->count = 1;

        $result = $this->sentenceAnalyser->getWordsFromSentence($inputSentence);

        $this->assertEquals([$expectedWord], $result);
    }
}
