version: '2'
services:
    php:
        build: ./php
        volumes:
            - ../api-src:/var/www/api
        depends_on:
            - mysql
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ../api-src:/var/www/api
            - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: dev_env_password
        ports:
            - "3333:3306"
